import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Toaster as ToasterSonner } from '@/components/ui/sonner'
import { Toaster } from '@/components/ui/toaster'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        {children}
        <ToasterSonner richColors />
        <Toaster />
      </body>
    </html>
  )
}
